[package]
name = "pbr-rust"
version = "0.1.0"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
clap = "3.0.0-beta.1"
rand_chacha = "0.2.2"
image = "0.23.4"
rayon = "1.3.0"
num_cpus = "1.13.0"
num-traits = "0.2.12"
float-cmp = "0.8.0"

[dev-dependencies]
proptest = "0.10.0"
