[package]
name = "pbr-rust"
version = "0.1.0"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2018"

[features]
sampled-spectrum = []

[dependencies]
clap = "3.0.0-beta.1"
either = "1.6.0"
float-cmp = "0.8.0"
hexf = "0.1.0"
image = "0.23.4"
lazy_static = "1.4.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
rayon = "1.3.0"
num_cpus = "1.13.0"
num-traits = "0.2.12"
order-stat = "0.1.3"
typed-arena = "2.0.1"

[dev-dependencies]
proptest = "0.10.0"
